PROJECT_NAME = "cryptoFirstX1"
VERSION = "0.1.0"

NETWORK_MODE = "READ_ONLY"

REQUIRED_CONFIRMATIONS = 3

ALLOW_PRIVATE_KEY_EXPORT = False
ALLOW_REMOTE_SIGNING = False
ALLOW_AUTOMATIC_WITHDRAWALS = False
ALLOW_AUTOMATIC_CASHOUT = False
